# Generated by Django 6.0.5 on 2026-06-02 21:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.CharField(default='ASH Emran', max_length=100)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='Short description (max 500 characters)', max_length=500)),
                ('content', ckeditor.fields.RichTextField(help_text='Full blog content with rich text formatting')),
                ('image', models.ImageField(help_text='Blog cover image (will be used as OG image and thumbnail)', upload_to='blog_images/')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (60 characters recommended)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (160 characters recommended)', max_length=160)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for SEO', max_length=200)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title', max_length=100)),
                ('og_description', models.CharField(blank=True, help_text='Open Graph description', max_length=160)),
                ('is_published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ['-publish_date'],
            },
        ),
    ]
